INSERT INTO currency (created_date, updated_date, code)
VALUES
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'KZT'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'USD'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'EUR'),
    (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'RUB');
